# Generated by Django 4.1.7 on 2023-03-27 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='like',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
