# Generated by Django 4.1.7 on 2023-03-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_like_create_date_like_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
    ]
